#define SELF_TEST_X_GYRO 00 //RW
#define SELF_TEST_Y_GYRO 01 //RW
#define SELF_TEST_Z_GYRO 02 //RW
#define SELF_TEST_X_ACCEL 0D //RW
#define SELF_TEST_Y_ACCEL 0E //RW
#define SELF_TEST_Z_ACCEL 0F //RW
#define XG_OFFSET_H 13 //RW
#define XG_OFFSET_L 14 //RW
#define YG_OFFSET_H 15 //RW
#define YG_OFFSET_L 16 //RW
#define ZG_OFFSET_H 17 //RW
#define ZG_OFFSET_L 18 //RW
#define SMPLRT_DIV 19 //RW
#define CONFIG 1A //RW
#define GYRO_CONFIG 1B //RW
#define ACCEL_CONFIG 1C //RW
#define ACCEL_CONFIG2 1D //RW
#define LP_ACCEL_ODR 1E //RW
#define WOM_THR 1F //RW
#define FIFO_EN 23 //RW
#define I2C_MST_CTRL 24 //RW
#define I2C_SLV0_ADDR 25 //RW
#define I2C_SLV0_REG 26 //RW
#define I2C_SLV0_CTRL 27 //RW
#define I2C_SLV1_ADDR 28 //RW
#define I2C_SLV1_REG 29 //RW
#define I2C_SLV1_CTRL 2A //RW
#define I2C_SLV2_ADDR 2B //RW
#define I2C_SLV2_REG 2C //RW
#define I2C_SLV2_CTRL 2D //RW
#define I2C_SLV3_ADDR 2E //RW
#define I2C_SLV3_REG 2F //RW
#define I2C_SLV3_CTRL 30 //RW
#define I2C_SLV4_ADDR 31 //RW
#define I2C_SLV4_REG 32 //RW
#define I2C_SLV4_DO 33 //RW
#define I2C_SLV4_CTRL 34 //RW
#define I2C_SLV4_DI 35 //R
#define I2C_MST_STATUS 36 //R
#define INT_PIN_CFG 37 //RW
#define INT_ENABLE 38 //RW
#define INT_STATUS 3A //R
#define ACCEL_XOUT_H 3B //R
#define ACCEL_XOUT_L 3C //R
#define ACCEL_YOUT_H 3D //R
#define ACCEL_YOUT_L 3E //R
#define ACCEL_ZOUT_H 3F //R
#define ACCEL_ZOUT_L 40 //R
#define TEMP_OUT_H 41 //R
#define TEMP_OUT_L 42 //R
#define GYRO_XOUT_H 43 //R
#define GYRO_XOUT_L 44 //R
#define GYRO_YOUT_H 45 //R
#define GYRO_YOUT_L 46 //R
#define GYRO_ZOUT_H 47 //R
#define GYRO_ZOUT_L 48 //R
#define EXT_SENS_DATA_00 49 //R
#define EXT_SENS_DATA_01 4A //R
#define EXT_SENS_DATA_02 4B //R
#define EXT_SENS_DATA_03 4C //R
#define EXT_SENS_DATA_04 4D //R
#define EXT_SENS_DATA_05 4E //R
#define EXT_SENS_DATA_06 4F //R
#define EXT_SENS_DATA_07 50 //R
#define EXT_SENS_DATA_08 51 //R
#define EXT_SENS_DATA_09 52 //R
#define EXT_SENS_DATA_10 53 //R
#define EXT_SENS_DATA_11 54 //R
#define EXT_SENS_DATA_12 55 //R
#define EXT_SENS_DATA_13 56 //R
#define EXT_SENS_DATA_14 57 //R
#define EXT_SENS_DATA_15 58 //R
#define EXT_SENS_DATA_16 59 //R
#define EXT_SENS_DATA_17 5A //R
#define EXT_SENS_DATA_18 5B //R
#define EXT_SENS_DATA_19 5C //R
#define EXT_SENS_DATA_20 5D //R
#define EXT_SENS_DATA_21 5E //R
#define EXT_SENS_DATA_22 5F //R
#define EXT_SENS_DATA_23 60 //R
#define I2C_SLV0_DO 63 //RW
#define I2C_SLV1_DO 64 //RW
#define I2C_SLV2_DO 65 //RW
#define I2C_SLV3_DO 66 //RW
#define I2C_MST_DELAY_CTRL 67 //RW
#define SIGNAL_PATH_RESET 68 //RW
#define MOT_DETECT_CTRL 69 //RW
#define USER_CTRL 6A //RW
#define PWR_MGMT_1 6A //RW
#define PWR_MGMT_2 6B //RW
#define FIFO_COUNTH 72 //RW
#define FIFO_COUNTL 73 //RW
#define FIFO_R_W 74 //RW
#define WHO_AM_I 75 //R
#define XA_OFFSET_H 77 //RW
#define XA_OFFSET_L 78 //RW
#define YA_OFFSET_H 7A //RW
#define YA_OFFSET_L 7B //RW
#define ZA_OFFSET_H 7D //RW
#define ZA_OFFSET_L 7E //RW
//Magnetometer Register addresses. Unfused and accessible values are noted here.
#define WIA 00H //R
#define INFO 01H //R
#define ST1 02H //R
#define HXL 03H //R
#define HXH 04H //R
#define HYL 05H //R
#define HYH 06H //R
#define HZL 07H //R
#define HZH 08H //R
#define ST2 09H //R
#define CNTL 0AH //RW
#define ASTC 0CH //RW
#define I2CDIS 0FH //RW