#define SELF_TEST_X_GYRO    0x00    //RW
#define SELF_TEST_Y_GYRO    0x01    //RW
#define SELF_TEST_Z_GYRO    0x02    //RW
#define SELF_TEST_X_ACCEL   0x0D    //RW
#define SELF_TEST_Y_ACCEL   0x0E    //RW
#define SELF_TEST_Z_ACCEL   0x0F    //RW
#define XG_OFFSET_H         0x13    //RW
#define XG_OFFSET_L         0x14    //RW
#define YG_OFFSET_H         0x15    //RW
#define YG_OFFSET_L         0x16    //RW
#define ZG_OFFSET_H         0x17    //RW
#define ZG_OFFSET_L         0x18    //RW
#define SMPLRT_DIV          0x19    //RW
#define CONFIG              0x1A    //RW
#define GYRO_CONFIG         0x1B    //RW
#define ACCEL_CONFIG        0x1C    //RW
#define ACCEL_CONFIG2       0x1D    //RW
#define LP_ACCEL_ODR        0x1E    //RW
#define WOM_THR             0x1F    //RW
#define FIFO_EN             0x23    //RW
#define I2C_MST_CTRL        0x24    //RW
#define I2C_SLV0_ADDR       0x25    //RW
#define I2C_SLV0_REG        0x26    //RW
#define I2C_SLV0_CTRL       0x27    //RW
#define I2C_SLV1_ADDR       0x28    //RW
#define I2C_SLV1_REG        0x29    //RW
#define I2C_SLV1_CTRL       0x2A    //RW
#define I2C_SLV2_ADDR       0x2B    //RW
#define I2C_SLV2_REG        0x2C    //RW
#define I2C_SLV2_CTRL       0x2D    //RW
#define I2C_SLV3_ADDR       0x2E    //RW
#define I2C_SLV3_REG        0x2F    //RW
#define I2C_SLV3_CTRL       0x30    //RW
#define I2C_SLV4_ADDR       0x31    //RW
#define I2C_SLV4_REG        0x32    //RW
#define I2C_SLV4_DO         0x33    //RW
#define I2C_SLV4_CTRL       0x34    //RW
#define I2C_SLV4_DI         0x35    //R
#define I2C_MST_STATUS      0x36    //R
#define INT_PIN_CFG         0x37    //RW
#define INT_ENABLE          0x38    //RW
#define INT_STATUS          0x3A    //R
#define ACCEL_XOUT_H        0x3B    //R
#define ACCEL_XOUT_L        0x3C    //R
#define ACCEL_YOUT_H        0x3D    //R
#define ACCEL_YOUT_L        0x3E    //R
#define ACCEL_ZOUT_H        0x3F    //R
#define ACCEL_ZOUT_L        0x40    //R
#define TEMP_OUT_H          0x41    //R
#define TEMP_OUT_L          0x42    //R
#define GYRO_XOUT_H         0x43    //R
#define GYRO_XOUT_L         0x44    //R
#define GYRO_YOUT_H         0x45    //R
#define GYRO_YOUT_L         0x46    //R
#define GYRO_ZOUT_H         0x47    //R
#define GYRO_ZOUT_L         0x48    //R
#define EXT_SENS_DATA_00    0x49    //R
#define EXT_SENS_DATA_01    0x4A    //R
#define EXT_SENS_DATA_02    0x4B    //R
#define EXT_SENS_DATA_03    0x4C    //R
#define EXT_SENS_DATA_04    0x4D    //R
#define EXT_SENS_DATA_05    0x4E    //R
#define EXT_SENS_DATA_06    0x4F    //R
#define EXT_SENS_DATA_07    0x50    //R
#define EXT_SENS_DATA_08    0x51    //R
#define EXT_SENS_DATA_09    0x52    //R
#define EXT_SENS_DATA_10    0x53    //R
#define EXT_SENS_DATA_11    0x54    //R
#define EXT_SENS_DATA_12    0x55    //R
#define EXT_SENS_DATA_13    0x56    //R
#define EXT_SENS_DATA_14    0x57    //R
#define EXT_SENS_DATA_15    0x58    //R
#define EXT_SENS_DATA_16    0x59    //R
#define EXT_SENS_DATA_17    0x5A    //R
#define EXT_SENS_DATA_18    0x5B    //R
#define EXT_SENS_DATA_19    0x5C    //R
#define EXT_SENS_DATA_20    0x5D    //R
#define EXT_SENS_DATA_21    0x5E    //R
#define EXT_SENS_DATA_22    0x5F    //R
#define EXT_SENS_DATA_23    0x60    //R
#define I2C_SLV0_DO         0x63    //RW
#define I2C_SLV1_DO         0x64    //RW
#define I2C_SLV2_DO         0x65    //RW
#define I2C_SLV3_DO         0x66    //RW
#define I2C_MST_DELAY_CTRL  0x67    //RW
#define SIGNAL_PATH_RESET   0x68    //RW
#define MOT_DETECT_CTRL     0x69    //RW
#define USER_CTRL           0x6A    //RW
#define PWR_MGMT_1          0x6A    //RW
#define PWR_MGMT_2          0x6B    //RW
#define FIFO_COUNTH         0x72    //RW
#define FIFO_COUNTL         0x73    //RW
#define FIFO_R_W            0x74    //RW
#define WHO_AM_I            0x75    //R
#define XA_OFFSET_H         0x77    //RW
#define XA_OFFSET_L         0x78    //RW
#define YA_OFFSET_H         0x7A    //RW
#define YA_OFFSET_L         0x7B    //RW
#define ZA_OFFSET_H         0x7D    //RW
#define ZA_OFFSET_L         0x7E    //RW

//Magnetometer Register addresses.
//Unfused and accessible values are noted here.

#define WIA                 0x00    //R
#define INFO                0x01    //R
#define ST1                 0x02    //R
#define HXL                 0x03    //R
#define HXH                 0x04    //R
#define HYL                 0x05    //R
#define HYH                 0x06    //R
#define HZL                 0x07    //R
#define HZH                 0x08    //R
#define ST2                 0x09    //R
#define CNTL                0x0A    //RW
#define ASTC                0x0C    //RW
#define I2CDIS              0x0F    //RW
